//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.06.11 at 11:25:17 AM CEST
//
/**
 * WMS attribuut filter package.
 *
 * @since 1.6
 * @author mprins
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.wms.cbsviewer.mineleni.nl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.mineleni.cbsviewer.servlet.wms.xml;
