//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Generated on: 2013.11.19 at 02:07:02 PM CET 
//
/**
 * WMS lagen package.
 * 
 * @since 1.6
 * @author mprins
 */
@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.util.cbsviewer.mineleni.nl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.mineleni.cbsviewer.util.xml;

